node {

    checkout changelog: false, poll: false, scm: [
        $class: 'GitSCM',
        branches: [
            [name: '*/master']
        ], doGenerateSubmoduleConfigurations: false, extensions: [
            [$class: 'WipeWorkspace']
        ], submoduleCfg: [], userRemoteConfigs: [
            [url: 'https://github.com/vanelin/configuration-as-code-jenkins-k8s-pipeline.git']
        ]
    ]

    stage('Sanity') {
        sh 'echo Hello, World!'
    }

}
